//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sajt.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin
    {
        public int idadmin { get; set; }
        public string kor_ime { get; set; }
        public string lozinka { get; set; }
    }
}
