//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sajt.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu
    {
        public int idmenu { get; set; }
        public string naziv { get; set; }
        public string opis { get; set; }
        public int cena { get; set; }
    }
}
