//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sajt.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class poll
    {
        public int idpoll { get; set; }
        public string naziv { get; set; }
        public int glasovi { get; set; }
    }
}
